### ISSUE TITLE
What do you think about ansible?

### ISSUE THREAD

**Issue by robinlehrmann** [lacicloud/LaciCloud#2]
Hi, for your application, I would prefer to use a vagrant box with ansible provisioning scripts.
A good reason to use vagrant is, that you have a local development environment with one command locally. Additionally you can use your scripts to provisioning your server(s). Do have automated your deployment ? ansible can help.

**Comment by lacicloud** [comment]
Hey, Thanks for the suggestion, I don't have experience with Ansible though. I'll look into it.

**Comment by robinlehrmann** [comment]
You can take a look at my repository. https://github.com/robinlehrmann/symfony-minecraft-sponge
