### ISSUE TITLE
PSR-2 Standard and composer

### ISSUE THREAD

**Issue by robinlehrmann** [lacicloud/LaciCloud#3]
Hi, 
why you don't use this standards ? https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

That will help's you to have a clean software architecture and have namespaces and classes.
You don't need require_once in every file ;)

Use composer. That would save much time to maintain your code.

**Comment by lacicloud** [comment]
Thanks, I should probably learn how to use Composer. To be honest, I will probably not update LaciCloud to have Ansible support (your other issue) and Composer but I will definitely look into it for my next project.

As for coding style, I am a fan of my own.

**Comment by lacicloud** [comment]
@robinlehrmann hello again! Composer is in progress.
